before_install: wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz -O - | sudo tar -xJ --strip-components=1 -C /usr/local/bin/
language: ruby
rvm:
  - 2.0.0
  - 2.2
  - 2.3.1
  - 3.2.1
cache:
  - bundler
